version: "3.8"

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - uvicorn

  uvicorn:
    build:
      context: ./src/backend
    command: bash -c "./venv/bin/uvicorn main:app --port 8000 --host 0.0.0.0"